variables:
  - &minio-settings
    access_key:
      from_secret: minio_access_key
    secret_key:
      from_secret: minio_secret_key
    endpoint:
      from_secret: minio_endpoint
    path_style: true
    region: eu-central-jcm

steps:
  build:
    image: ubuntu:noble
    commands:
      - apt-get update
      - DEBIAN_FRONTEND=noninteractive apt-get install -y curl
      - mkdir -p /etc/apt/keyrings
      - curl https://apt.llvm.org/llvm-snapshot.gpg.key -o /etc/apt/keyrings/llvm.asc
      - echo "deb [signed-by=/etc/apt/keyrings/llvm.asc] http://apt.llvm.org/noble/ llvm-toolchain-noble main" > /etc/apt/sources.list.d/llvm.list
      - apt-get update
      - >-
        DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends
        clang-20 clang-tools-20 cmake ninja-build git glslang-tools xxd patch curl gettext ca-certificates libglib2.0-bin
        libvulkan-dev pkg-config libsystemd-dev libsdl2-dev libsdl2-mixer-dev libsdl2-image-dev libglm-dev
        libspdlog-dev libfreetype-dev libglibmm-2.68-dev libsdbus-c++-dev libboost-dev
      - .woodpecker/download_unlicensed.sh
      - >-
        cmake -B build -G Ninja
        -DCMAKE_C_COMPILER=clang-20 -DCMAKE_CXX_COMPILER=clang++-20
        -DCMAKE_BUILD_TYPE=Debug
      - cmake --build build --parallel 2
      - glib-compile-schemas schemas
  test:
    image: ubuntu:noble
    commands:
      - apt-get update
      - >-
        DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends
        xvfb dbus-x11 mesa-vulkan-drivers libsdl2-2.0-0 libsdl2-mixer-2.0-0 libsdl2-image-2.0-0
        libspdlog1.12 libglibmm-2.68-1t64 libsdbus-c++1
        vulkan-validationlayers ffmpeg fonts-ubuntu xdotool
      - ./test/record_video.sh
    volumes:
      - /dev/dri/renderD128:/dev/dri/renderD128
    privileged: true
  upload:
    image: woodpeckerci/plugin-s3
    settings:
      <<: *minio-settings
      bucket: woodpecker
      source: build/test-*
      strip_prefix: build/
      target: /artifacts/${CI_REPO}/${CI_PIPELINE_NUMBER}/public/
    when:
      - status: [ success, failure ]
  upload-branch:
    image: woodpeckerci/plugin-s3
    settings:
      <<: *minio-settings
      bucket: woodpecker
      source: build/test-output.webm
      strip_prefix: build/
      target: /artifacts/${CI_REPO}/${CI_COMMIT_BRANCH}/public/
