variables:
  - &minio-settings
    access_key:
      from_secret: minio_access_key
    secret_key:
      from_secret: minio_secret_key
    endpoint:
      from_secret: minio_endpoint
    path_style: true
    region: eu-central-jcm

steps:
  restore-cache:
    image: meltwater/drone-cache
    settings:
      <<: *minio-settings
      bucket: woodpecker-cache
      restore: true
      mount:
        - 'ccache'
  build:
    image: git.jcm.re/jcm/xmbshell:build
    pull: true
    commands:
      - .woodpecker/download_unlicensed.sh
      - export CCACHE_DIR="$PWD/ccache"
      - export CCACHE_MAXSIZE=2G
      - >-
        cmake -B build -G Ninja
        -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        -DDOWNLOAD_DEPENDENCIES_SHALLOW=ON
        -DCMAKE_BUILD_TYPE=DebugAsan
      - cmake --build build --parallel 2
      - glib-compile-schemas schemas
  rebuild-cache:
    image: meltwater/drone-cache
    settings:
      <<: *minio-settings
      bucket: woodpecker-cache
      rebuild: true
      mount:
        - 'ccache'
  test:
    image: git.jcm.re/jcm/xmbshell:test
    pull: true
    commands:
      - ./test/record_video.sh
  upload:
    image: woodpeckerci/plugin-s3
    settings:
      <<: *minio-settings
      bucket: woodpecker
      source: build/test-*
      strip_prefix: build/
      target: /artifacts/${CI_REPO}/${CI_PIPELINE_NUMBER}/public/
    when:
      - status: [ success, failure ]
  upload-branch:
    image: woodpeckerci/plugin-s3
    settings:
      <<: *minio-settings
      bucket: woodpecker
      source: build/test-output.mp4
      strip_prefix: build/
      target: /artifacts/${CI_REPO}/${CI_COMMIT_BRANCH}/public/

depends_on:
  - build-image
  - test-image
